#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

SETTINGS_FILE="/etc/specific/serial.conf"

# Function to switch current termination_resistor to configured setting.
# Return: 0 on success, unequal to 0 otherwise
update_current_termination_resistor()
{
	local termination_resistor_value="$(grep "termination_resistor" $SETTINGS_FILE | cut -d= -f2)"
	/etc/config-tools/config_serial_interface -s termination_resistor=$termination_resistor_value
}

# Function to switch current bias network to configured setting.
# Return: 0 on success, unequal to 0 otherwise
update_current_bias_network()
{
	local bias_network_value="$(grep "bias_network" $SETTINGS_FILE | cut -d= -f2)"
	/etc/config-tools/config_serial_interface -s bias_network=$bias_network_value
}

case $1 in

  start)
    if [ -e "$SETTINGS_FILE" ]; then
       update_current_termination_resistor
       update_current_bias_network
    fi
  ;;
  stop)
  ;;
esac
