#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG



function log
{
    /usr/bin/logger -s -t networking-finish "$@"
}


case "$1" in
start)
    /etc/config-tools/config_eth_leds 
    ;;
stop)
    ;;
reload)
    ;;
restart|force-reload)
    ;;
*)
    N=$BASH_COMMAND
    echo "usage: $N {start|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
